-- Tables

-- DROP TABLE PARTICIPANTE;
-- DROP TABLE VENDEDOR;
-- DROP TABLE USUARIO;

CREATE TABLE USUARIO(
	cpfCnpj			VARCHAR(50) 	PRIMARY KEY NOT NULL,
	nome 			VARCHAR(50) 	NOT NULL,
	email 			VARCHAR(50) 	NOT NULL,
	senha			VARCHAR(50) 	NOT NULL,
	enderecoRua		VARCHAR(50) 	NOT NULL,
	enderecoNumero  VARCHAR(50) 	NOT NULL
);

CREATE TABLE PARTICIPANTE(
	cpfCnpj			VARCHAR(50) 	REFERENCES USUARIO (cpfCnpj) PRIMARY KEY NOT NULL,
	nome 			VARCHAR(50) 	NOT NULL,
	email 			VARCHAR(50) 	NOT NULL,
	senha			VARCHAR(50) 	NOT NULL,
	enderecoRua		VARCHAR(50) 	NOT NULL,
	enderecoNumero  VARCHAR(50) 	NOT NULL
);

CREATE TABLE VENDEDOR(
	cpfCnpj			VARCHAR(50) 	REFERENCES USUARIO (cpfCnpj) PRIMARY KEY NOT NULL,
	nome 			VARCHAR(50) 	NOT NULL,
	email 			VARCHAR(50) 	NOT NULL,
	senha			VARCHAR(50) 	NOT NULL,
	enderecoRua		VARCHAR(50) 	NOT NULL,
	enderecoNumero  VARCHAR(50) 	NOT NULL
);